apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: katalon_android
spec:
  replicas: 1 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: katalon_android
  template:
    metadata:
      labels:
        app: katalon_android
    spec:
      containers:
        - name: android-emulator #The name of the android emulator container
          image: vaibhavx7/android-emulator:latest #The Docker image for building the android emulator container
          ports:
          - containerPort: 4725 #The port for android emulator container
          args:
            - bash
            - -c
            - |
              ./start_emu_headless.sh
              tail -f /dev/null
          env:
            - name: APPIUM_PORT
              value: "4725"
          securityContext:
              privileged: true
          stdin: true
          tty: true

        - name: katalon #The name of the katalon container
          image: vaibhavx7/katalon:latest #The Docker image for building the katalon container
          ports:
          - containerPort: 3000 #The port for the katalon container
